import re
from playwright.sync_api import Page, expect
from time import sleep


def test_example(context) -> None:
    page: Page = context.new_page()
    page.goto("https://www.letu.ru/")
    page.set_viewport_size({"width": 1650, "height": 1200})
    sleep(5)
    button_2(page)


def button_2(page: Page):
    page.query_selector('[href="/brands"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/ecards"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/podarki/tsvety"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/russian-brands"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/korea"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/prof"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/clean-beauty"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/apteka"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/club"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/vse-dlya-doma"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/tovary-dlya-sporta"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    print('<<<<<The test is passed!>>>>>')
