import re
from playwright.sync_api import Page, Playwright, sync_playwright
from time import sleep


def test_example(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.letu.ru/")
    page.set_viewport_size({"width": 1650, "height": 1200})
    sleep(5)

    page.locator(".le-icon").first.click()
    page.locator(".le-modal__btn-close").click()
    page.get_by_text("Москва (в пределах МКАД)").click()
    sleep(1)
    page.locator(".le-modal__btn-close").click()
    page.get_by_role("link", name="Магазины").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.locator("#header").get_by_role("link", name="Связаться с нами").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_text("Москва (в пределах МКАД) Магазины Связаться с нами Клубная программа Блог RU").click()
    sleep(1)
    page.get_by_role("link", name="Клубная программа").first.click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Блог").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_text("RU", exact=True).click()
    page.get_by_text("中文 — CN").click()
    page.locator("div").filter(has_text="Москва (в пределах МКАД) Магазины Связаться с нами Клубная программа Блог CN").nth(2).click()
    page.get_by_text("Москва (в пределах МКАД) Магазины Связаться с нами Клубная программа Блог CN").click()
    page.get_by_text("Связаться с нами Клубная программа Блог").click()
    page.get_by_text("CN", exact=True).click()
    page.get_by_text("Русский — RU").click()
    page.get_by_role("button", name="Каталог").click()
    page.get_by_placeholder("Поиск").click()
    page.locator("#search-form svg").click()
    page.get_by_placeholder("Поиск").click()
    page.get_by_role("button", name="Найти").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_text("Войти Войдите или зарегистрируйтесь Войти, чтобы увидеть цены с учетом твоих ски").click()
    sleep(1)
    page.get_by_role("link", name="Избранное").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Корзина").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="parfyumeriya Парфюмерия").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Нишевая парфюмерия Нишевая парфюмерия").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Акция Акция").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Уход за лицом Уход за лицом").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Уход за телом Уход за телом").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Уход за волосами Уход за волосами").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Маски и патчи Маски и патчи").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Макияж Макияж").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Техника для красоты Техника для красоты").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Аптечная косметика Аптечная косметика").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Подарочный сертификат Подарочный сертификат").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Цветы Цветы").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    page.get_by_role("link", name="Акции").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(1)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    print('<<<<<Первый тест пройден!>>>>>')

    page.wait_for_selector('[href="/brands",]', timeout=10000).click()
    print('brands')
    sleep(3)
    page.wait_for_selector("button", name="L'Etoile", timeout=10000).click()
    sleep(3)
    page.wait_for_selector('[href="/ecards"]', timeout=10000).click()
    print('ecards')
    sleep(3)
    page.wait_for_selector("button", name="L'Etoile", timeout=10000).click()
    sleep(3)
    page.wait_for_selector('[href="/browse/podarki/tsvety"]', timeout=10000).click()
    print('tsvety')
    sleep(3)
    page.wait_for_selector("button", name="L'Etoile", timeout=10000).click()
    sleep(3)
    page.query_selector('[href="/compilations/russian-brands"]').click()
    print('russian-brands')
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/korea"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/prof"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/compilations/clean-beauty"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/apteka"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/club"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/vse-dlya-doma"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    sleep(3)
    page.query_selector('[href="/browse/tovary-dlya-sporta"]').click()
    sleep(3)
    page.get_by_role("button", name="L'Etoile").click()
    print('<<<<<Второй тест пройден!>>>>>')

    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.locator("a").filter(has_text="Посмотреть").click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="Letoile").click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="DG").click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="CLB").click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="NARS").first.click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="Antonio Maretti", exact=True).click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="Lanvin").click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    page.get_by_role("link", name="Trussardi").click()
    page.get_by_role("button", name="L'Etoile").click()
    sleep(2)
    for p in range(7):
        page.keyboard.press("ArrowDown")
    try:
        page.get_by_role("link", name="Pen").click()
        page.get_by_role("button", name="L'Etoile").click()
    except:
        for p in range(7):
            page.keyboard.press("ArrowDown")
        page.get_by_role("button", name="Все бренды").click()
        page.get_by_role("button", name="L'Etoile").click()
    print('<<<<<Третий тест пройден!>>>>>')
